language: java
jdk:
 - openjdk8
 - openjdk12
addons:
  sonarcloud:
    organization: "danthe1st"
script:
  - mvn test -B
  - mvn spotbugs:check
  - sonar-scanner -Dsonar.projectKey=danthe1st_DanBot1 -Dsonar.organization=danthe1st -Dsonar.host.url=https://sonarcloud.io