language: java
jobs:
  include:
    - stage: Test - Java-8
      name: Java 8
      jdk:
      - openjdk8
      script:
        - mvn test -B
    - stage: Test - Java-12
      name: Java 12
      jdk:
      - openjdk12
      script:
        - mvn test -B
    - stage: code analysis
      name: spotbugs
      jdk:
      - openjdk8
      script:
        - mvn spotbugs:check
    - name: SonarLint
      jdk:
      - openjdk8
      addons:
        sonarcloud:
          organization: "danthe1st"
      script:
        - sonar-scanner -Dsonar.projectKey=danthe1st_DanBot1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=src/ -Dsonar.java.binaries=target/ -Dsonar.java.libraries=target/
    - stage: "Upload to Wiki"
      before_install:
      - openssl aes-256-cbc -K $encrypted_f8dd8f761714_key -iv $encrypted_f8dd8f761714_iv -in github_deploy_key.enc -out github_deploy_key -d
      - chmod 600 github_deploy_key
      - eval $(ssh-agent -s)
      - ssh-add github_deploy_key
      jdk:
      - openjdk8
      script:
        - chmod +x ./saveJAR.sh
        - ./saveJAR.sh
      if: branch = master