language: java
jobs:
  include:
    - stage: test
      jdk:
       - openjdk8
       - openjdk12
      addons:
        sonarcloud:
          organization: "danthe1st"
      script:
        - mvn test -B
    - stage: code analysis
        - mvn spotbugs:check
        - sonar-scanner -Dsonar.projectKey=danthe1st_DanBot1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=. -Dsonar.java.binaries=.