language: java
jobs:
  include:
    - name: test
      jdk:
      - openjdk8
      script:
        - mvn test -B
    - jdk:
      - openjdk12
      script:
        - mvn test -B
    - stage: code analysis
      jdk:
      - openjdk8
      addons:
        sonarcloud:
          organization: "danthe1st"
      script:
        - mvn spotbugs:check
        - sonar-scanner -Dsonar.projectKey=danthe1st_DanBot1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=. -Dsonar.java.binaries=.
    - stage: "Upload to Wiki"
      jdk:
      - openjdk12
      script:
        - chmod +x ./saveJAR.sh
        - ./saveJAR.sh